version: "3.8"
services:
    postgres:
        container_name: ${DB_NAME}-postgres
        image: postgres:14.3
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        user: postgres
        ports:
            - "${DB_PORT}:5432"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 1s
            timeout: 1s
            retries: 30
        restart: unless-stopped
    flyway:
        image: flyway/flyway:9.3.1
        command: -url=jdbc:postgresql://host.docker.internal:${DB_PORT}/${POSTGRES_DB} -user=${DB_USER} -password=${DB_PASSWORD} migrate
        volumes:
            - ./migrations:/flyway/sql
        depends_on:
            postgres:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"
    express:
        container_name: ${DB_NAME}-express
        build: .
        command: >
            sh -c "node server.js"
        ports:
            - "${APP_PORT}:${APP_PORT}"
        env_file: .env
        environment:
            POSTGRES_HOST: host.docker.internal
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"